import {THREE,rand,banner} from '../core/utils.js';
export class MissionSystem{constructor(game){this.game=game;this.active=null;this.marker=null;this.timer=0;}
startRandom(){if(this.active){banner('MISSION ALREADY ACTIVE');return}const types=['Delivery','Assassination','Race','Escort'];this.start(types[Math.floor(Math.random()*types.length)])}
start(type){const g=this.game;this.clearMarker();const target=new THREE.Vector3(rand(-220,220),0,rand(-220,220));this.active={type,target,progress:0,done:false};this.timer=type==='Race'?1250:type==='Escort'?1550:0;this.marker=new THREE.Mesh(new THREE.CylinderGeometry(4,4,.2,24),new THREE.MeshStandardMaterial({color:0xffff00,emissive:0xffff00,emissiveIntensity:1,transparent:true,opacity:.65}));this.marker.position.copy(target);this.marker.position.y=.12;g.scene.add(this.marker);if(type==='Assassination'){const boss=g.spawnEnemy(target.x,target.z,'boss');boss.missionBoss=true}if(type==='Escort'){const npc=new THREE.Mesh(new THREE.BoxGeometry(1,1.8,1),new THREE.MeshStandardMaterial({color:0xffaa00,emissive:0x553300}));npc.position.copy(g.player.position).add(new THREE.Vector3(3,.9,3));g.scene.add(npc);this.active.npc=npc;this.active.npcHp=100}banner('MISSION: '+type.toUpperCase())}
update(dt){if(!this.active)return;const g=this.game,a=this.active;if(this.marker)this.marker.rotation.y+=.03*dt;if(a.type==='Delivery'&&g.player.position.distanceTo(a.target)<5)this.complete(520);if(a.type==='Race'){this.timer-=dt;if(g.player.position.distanceTo(a.target)<5)this.complete(950);else if(this.timer<=0)this.fail()}if(a.type==='Assassination'){const alive=g.cops.some(c=>c.missionBoss);if(!alive)this.complete(1050)}if(a.type==='Escort'){this.timer-=dt;if(a.npc){const dx=g.player.position.x-a.npc.position.x,dz=g.player.position.z-a.npc.position.z,d=Math.hypot(dx,dz);if(d>4){a.npc.position.x+=dx/d*(g.TUNING?.ESCORT_SPEED||.009)*dt*60;a.npc.position.z+=dz/d*(g.TUNING?.ESCORT_SPEED||.009)*dt*60}for(const c of g.cops)if(c.mesh.position.distanceTo(a.npc.position)<2)a.npcHp-=.055*dt;if(a.npcHp<=0)this.fail()}if(g.player.position.distanceTo(a.target)<5)this.complete(950);else if(this.timer<=0)this.fail()}}
complete(reward){const g=this.game;g.score+=reward;g.cash+=reward;g.save.addCash(reward);g.save.addSkill(1);g.heatSystem.add(1);banner('MISSION COMPLETE +$'+reward,'green');this.end()}
fail(){banner('MISSION FAILED','red');this.end()}
end(){if(this.active?.npc)this.game.scene.remove(this.active.npc);this.clearMarker();this.active=null}
clearMarker(){if(this.marker){this.game.scene.remove(this.marker);this.marker=null}}}
