import {THREE,clamp,banner,boxAt} from './core/utils.js';
import {SaveSystem} from './systems/SaveSystem.js';import {MapSystem} from './systems/MapSystem.js';import {WeaponSystem} from './systems/WeaponSystem.js';import {GrenadeSystem} from './systems/GrenadeSystem.js';import {LootSystem} from './systems/LootSystem.js';import {HeatSystem} from './systems/HeatSystem.js';import {MissionSystem} from './systems/MissionSystem.js';
const game={};window.game=game;game.scene=new THREE.Scene();game.scene.background=new THREE.Color(0x030610);game.scene.fog=new THREE.Fog(0x030610,80,330);game.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,1000);game.renderer=new THREE.WebGLRenderer({antialias:true});game.renderer.setPixelRatio(Math.min(devicePixelRatio,2));game.renderer.setSize(innerWidth,innerHeight);document.body.appendChild(game.renderer.domElement);game.scene.add(new THREE.AmbientLight(0x162044,2));const sun=new THREE.DirectionalLight(0xffffff,1.1);sun.position.set(40,80,20);game.scene.add(sun);
game.yaw=0;game.pitch=0;game.locked=false;game.started=false;game.keys={};game.cops=[];game.helicopters=[];game.roadblocks=[];game.tracers=[];game.fx=[];game.score=0;game.kills=0;game.cash=0;
// V10.3 Cruise City tuning: lower = slower. Edit these if you want the game even more chill or faster.
game.TUNING={PLAYER_WALK:.0048,PLAYER_SPRINT:.0074,COP_SPEED:.00285,SWAT_SPEED:.00315,VAN_SPEED:.00255,BOSS_SPEED:.00245,HELI_SPEED:.00175,CAR_MAX:.0148,CAR_ACCEL:.00026,CAR_FRICTION:.974,CAR_TURN:.0155,CAR_RAM_SPEED:.0078,ESCORT_SPEED:.0062};
game.save=new SaveSystem(game);game.cash=game.save.data.cash||0;game.maxHp=100+(game.save.data.upgrades.maxHp||0)*10;game.maxArmor=100+(game.save.data.upgrades.armor||0)*15;game.hp=game.maxHp;game.armor=Math.min(50,game.maxArmor);
game.pivot=new THREE.Object3D();game.pitchObj=new THREE.Object3D();game.pivot.add(game.pitchObj);game.pitchObj.add(game.camera);game.camera.position.set(0,10,14);game.camera.lookAt(0,0,0);game.scene.add(game.pivot);
game.map=new MapSystem(game);game.weapons=new WeaponSystem(game);game.grenades=new GrenadeSystem(game);game.loot=new LootSystem(game);game.heatSystem=new HeatSystem(game);game.missions=new MissionSystem(game);
const pm=new THREE.MeshStandardMaterial({color:0x00ffff,emissive:0x003333,emissiveIntensity:.7});game.player=new THREE.Mesh(new THREE.BoxGeometry(1,1.8,1),pm);game.player.position.set(0,.9,0);game.scene.add(game.player);
const car=new THREE.Group();const cb=new THREE.Mesh(new THREE.BoxGeometry(3.2,.75,1.65),new THREE.MeshStandardMaterial({color:0xff3300,emissive:0x441100,emissiveIntensity:.4}));cb.position.y=.65;car.add(cb);const cr=new THREE.Mesh(new THREE.BoxGeometry(1.7,.55,1.3),new THREE.MeshStandardMaterial({color:0xcc2200,emissive:0x220400,emissiveIntensity:.25}));cr.position.y=1.2;car.add(cr);
// V10.3 car polish: wheels, headlights, brake lights, underglow.
for(const [wx,wz] of [[-1.15,-.9],[1.15,-.9],[-1.15,.9],[1.15,.9]]){const wh=new THREE.Mesh(new THREE.CylinderGeometry(.32,.32,.25,14),new THREE.MeshStandardMaterial({color:0x050505,roughness:.45,metalness:.25}));wh.rotation.z=Math.PI/2;wh.position.set(wx,.28,wz);car.add(wh)}
for(const x of [-.85,.85]){const h=new THREE.Mesh(new THREE.BoxGeometry(.34,.18,.08),new THREE.MeshBasicMaterial({color:0xffffaa}));h.position.set(x,.68,-.86);car.add(h);const t=new THREE.Mesh(new THREE.BoxGeometry(.32,.15,.08),new THREE.MeshBasicMaterial({color:0xff0022}));t.position.set(x,.64,.86);car.add(t)}
const under=new THREE.PointLight(0xff3300,.75,5);under.position.set(0,.25,0);car.add(under);const headGlow=new THREE.PointLight(0xffffaa,1.1,10);headGlow.position.set(0,.75,-1.25);car.add(headGlow);car.position.set(7,.05,7);game.scene.add(car);game.car=car;game.inCar=false;game.carSpeed=0;game.carAngle=0;
function moveObj(obj,nx,nz,sx=1,sz=1){if(game.map.collides(nx,nz,sx,sz))return false;obj.position.x=clamp(nx,-255,255);obj.position.z=clamp(nz,-255,255);return true}
game.spawnEnemy=(x,z,type='cop')=>{for(let tries=0;tries<20&&game.map.collides(x,z,2,2);tries++){x+=Math.random()*12-6;z+=Math.random()*12-6}const col=type==='swat'?0x1111ff:type==='boss'?0xff00ff:type==='van'?0x111133:0x2244ff;const mat=new THREE.MeshStandardMaterial({color:col,emissive:col,emissiveIntensity:.28});const mesh=new THREE.Mesh(new THREE.BoxGeometry(type==='boss'?1.5:1, type==='boss'?2.3:1.8, type==='boss'?1.5:1),mat);mesh.position.set(x,type==='boss'?1.15:.9,z);game.scene.add(mesh);const speed=type==='swat'?game.TUNING.SWAT_SPEED:type==='boss'?game.TUNING.BOSS_SPEED:game.TUNING.COP_SPEED;const c={mesh,hp:type==='swat'?4:type==='boss'?18:2,type,speed,score:type==='swat'?180:type==='boss'?1200:100,emp:0,stuck:0};game.cops.push(c);return c}
game.killEnemy=(e)=>{const arr=game.helicopters.includes(e)?game.helicopters:game.cops;const idx=arr.indexOf(e);if(idx>=0)arr.splice(idx,1);game.scene.remove(e.mesh);game.score+=e.score||100;game.kills++;game.cash+=20;game.save.addCash(20);if(Math.random()<.65){const lp=e.mesh.position.clone();lp.y=.55;game.loot.spawn(lp)}game.heatSystem.add(.10)};
game.spawnTracer=(from,to,col)=>{const geo=new THREE.BufferGeometry().setFromPoints([from.clone().add(new THREE.Vector3(0,.8,0)),to]);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:col,transparent:true,opacity:1}));game.scene.add(line);game.tracers.push({line,life:8})};game.spawnExplosion=(pos,radius,col)=>{const mesh=new THREE.Mesh(new THREE.SphereGeometry(radius,24,12),new THREE.MeshBasicMaterial({color:col,transparent:true,opacity:.35,wireframe:true}));mesh.position.copy(pos);game.scene.add(mesh);game.fx.push({mesh,life:18})};
function toggleCar(){if(game.inCar){game.inCar=false;game.player.position.set(game.car.position.x+2.6,.9,game.car.position.z);return}if(game.player.position.distanceTo(game.car.position)<4)game.inCar=true;else banner('GET CLOSER TO THE CAR','red')}
addEventListener('keydown',e=>{game.keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='r')game.weapons.reloadNow();if(e.key.toLowerCase()==='e')toggleCar();if(e.key.toLowerCase()==='q')game.grenades.cycle();if(e.key.toLowerCase()==='g')game.grenades.throw();if(e.key.toLowerCase()==='m')game.missions.startRandom();if(e.key.toLowerCase()==='u'){const p=game.save.buyRandom();if(p){game.maxHp=100+(game.save.data.upgrades.maxHp||0)*10;game.maxArmor=100+(game.save.data.upgrades.armor||0)*15;banner('UPGRADE: '+p.toUpperCase(),'green')}else banner('NEED $250','red')}if('12345'.includes(e.key))game.weapons.select(Number(e.key))});addEventListener('keyup',e=>game.keys[e.key.toLowerCase()]=false);
document.addEventListener('pointerlockchange',()=>game.locked=document.pointerLockElement===game.renderer.domElement);document.addEventListener('mousemove',e=>{if(!game.locked)return;game.yaw-=e.movementX*.0022;game.pitch=clamp(game.pitch+e.movementY*.0015,-.35,.75);game.pivot.rotation.y=game.yaw;game.pitchObj.rotation.x=-game.pitch});document.addEventListener('click',()=>{if(game.started&&game.locked)game.weapons.fire()});document.getElementById('startBtn').onclick=()=>{game.renderer.domElement.requestPointerLock();document.getElementById('start').style.display='none';game.started=true;for(let i=0;i<4;i++){const a=Math.random()*Math.PI*2,d=75+Math.random()*25;game.spawnEnemy(game.player.position.x+Math.cos(a)*d,game.player.position.z+Math.sin(a)*d,'cop')}banner('SURVIVE THE CITY — SLOWER, CLEANER, MEANER')};
function updatePlayer(dt){const fwd=new THREE.Vector3(-Math.sin(game.yaw),0,-Math.cos(game.yaw)),right=new THREE.Vector3(Math.cos(game.yaw),0,-Math.sin(game.yaw));let mx=0,mz=0;if(game.keys.w){mx+=fwd.x;mz+=fwd.z}if(game.keys.s){mx-=fwd.x;mz-=fwd.z}if(game.keys.a){mx-=right.x;mz-=right.z}if(game.keys.d){mx+=right.x;mz+=right.z}const l=Math.hypot(mx,mz);if(l){mx/=l;mz/=l}if(game.inCar){const max=game.TUNING.CAR_MAX+(game.save.data.upgrades.car||0)*.003,acc=game.TUNING.CAR_ACCEL+(game.save.data.upgrades.car||0)*.00012;if(game.keys.w)game.carSpeed=Math.min(max,game.carSpeed+acc*(game.keys.shift?1.35:1));else if(game.keys.s)game.carSpeed=Math.max(-max*.45,game.carSpeed-acc);else game.carSpeed*=game.TUNING.CAR_FRICTION;if(Math.abs(game.carSpeed)>.0015){if(game.keys.a)game.carAngle+=game.TUNING.CAR_TURN*(game.carSpeed>0?1:-1);if(game.keys.d)game.carAngle-=game.TUNING.CAR_TURN*(game.carSpeed>0?1:-1)}const nx=game.car.position.x-Math.sin(game.carAngle)*game.carSpeed*dt*60,nz=game.car.position.z-Math.cos(game.carAngle)*game.carSpeed*dt*60;if(!moveObj(game.car,nx,nz,3.2,1.65) || game.roadblocks.some(r=>{const b=new THREE.Box3().setFromObject(r.mesh);return b.containsPoint(new THREE.Vector3(nx,.8,nz));}))game.carSpeed*=-.25;game.car.rotation.y=game.carAngle;game.player.position.set(game.car.position.x,.9,game.car.position.z);for(const c of [...game.cops])if(Math.abs(game.carSpeed)>game.TUNING.CAR_RAM_SPEED&&c.mesh.position.distanceTo(game.car.position)<3.2)c.hp-=.32*dt}else{const spd=(game.keys.shift?game.TUNING.PLAYER_SPRINT:game.TUNING.PLAYER_WALK)*dt*60;if(mx||mz)moveObj(game.player,game.player.position.x+mx*spd,game.player.position.z+mz*spd)}const target=game.inCar?game.car.position:game.player.position;game.pivot.position.set(target.x,0,target.z)}
function updateAI(dt){for(let i=game.cops.length-1;i>=0;i--){const c=game.cops[i];if(c.hp<=0){game.killEnemy(c);continue}if(c.emp>0){c.emp-=dt;continue}const dx=game.player.position.x-c.mesh.position.x,dz=game.player.position.z-c.mesh.position.z,d=Math.hypot(dx,dz)||1;c.mesh.rotation.y=Math.atan2(dx,dz);let nx=c.mesh.position.x+dx/d*c.speed*dt*60,nz=c.mesh.position.z+dz/d*c.speed*dt*60;if(game.map.collides(nx,nz,c.type==='van'?3.8:1,c.type==='van'?2.2:1)){c.stuck++;nx=c.mesh.position.x+dz/d*c.speed*dt*45;nz=c.mesh.position.z-dx/d*c.speed*dt*45;if(game.map.collides(nx,nz,1,1)){nx=c.mesh.position.x-dz/d*c.speed*dt*45;nz=c.mesh.position.z+dx/d*c.speed*dt*45}}moveObj(c.mesh,nx,nz,c.type==='van'?3.8:1,c.type==='van'?2.2:1);if(d<1.7){let dmg=c.type==='swat'?.38:c.type==='boss'?.65:.25;takeDamage(dmg*dt)}}for(let i=game.helicopters.length-1;i>=0;i--){const h=game.helicopters[i];if(h.hp<=0){game.killEnemy(h);continue}h.mesh.children[1].rotation.y+=.8*dt;if(h.emp>0){h.emp-=dt;continue}const dx=game.player.position.x-h.mesh.position.x,dz=game.player.position.z-h.mesh.position.z,d=Math.hypot(dx,dz)||1;h.mesh.position.x+=dx/d*h.speed*dt*60;h.mesh.position.z+=dz/d*h.speed*dt*60;h.shoot-=dt;if(d<70&&h.shoot<=0){h.shoot=80;takeDamage(5);game.spawnTracer(h.mesh.position,game.player.position,0xff0000)}}for(let i=game.roadblocks.length-1;i>=0;i--){const r=game.roadblocks[i];r.life-=dt;if(r.life<=0){game.scene.remove(r.mesh);game.roadblocks.splice(i,1)}}}
function takeDamage(n){let left=n;if(game.armor>0){const a=Math.min(game.armor,left);game.armor-=a;left-=a*.65}game.hp=Math.max(0,game.hp-left);if(game.hp<=0)death()}
function death(){document.exitPointerLock?.();document.getElementById('death').style.display='flex';document.getElementById('deathStats').textContent=`Score ${game.score} | Kills ${game.kills} | Cash saved $${game.save.data.cash} | Skill ${game.save.data.skill}`;game.started=false}
function updateUI(){const w=game.weapons.weapon();document.getElementById('hp').textContent=Math.ceil(game.hp);document.getElementById('armor').textContent=Math.ceil(game.armor);document.getElementById('hpFill').style.width=(game.hp/game.maxHp*100)+'%';document.getElementById('armorFill').style.width=(game.armor/game.maxArmor*100)+'%';document.getElementById('weapon').textContent=w.name;document.getElementById('ammo').textContent=w.clip;document.getElementById('reserve').textContent=w.ammo;document.getElementById('grenade').textContent=game.grenades.type();document.getElementById('grenades').textContent=game.grenades.inv[game.grenades.type()]||0;const h=Math.floor(game.heatSystem.heat);document.getElementById('heat').textContent='★'.repeat(h)+'☆'.repeat(5-h);document.getElementById('cash').textContent=game.save.data.cash;document.getElementById('skill').textContent=game.save.data.skill;document.getElementById('score').textContent=game.score;document.getElementById('kills').textContent=game.kills;document.getElementById('district').textContent=game.map.districtName(game.player.position.x,game.player.position.z);document.getElementById('mission').textContent=game.missions.active?game.missions.active.type:'Press M'}
const mini=document.getElementById('mini'),ctx=mini.getContext('2d');function drawMini(){ctx.fillStyle='rgba(0,0,0,.85)';ctx.fillRect(0,0,170,170);ctx.strokeStyle='#0ff';ctx.strokeRect(0,0,170,170);const sc=.28;for(const b of game.map.buildings){const x=85+(b.position.x-game.player.position.x)*sc,y=85+(b.position.z-game.player.position.z)*sc;if(x>0&&x<170&&y>0&&y<170){ctx.fillStyle='#234';ctx.fillRect(x-2,y-2,4,4)}}for(const c of game.cops){const x=85+(c.mesh.position.x-game.player.position.x)*sc,y=85+(c.mesh.position.z-game.player.position.z)*sc;if(x>0&&x<170&&y>0&&y<170){ctx.fillStyle=c.type==='swat'?'#69f':c.type==='boss'?'#f0f':'#f33';ctx.fillRect(x-2,y-2,4,4)}}for(const d of game.loot.drops){const x=85+(d.mesh.position.x-game.player.position.x)*sc,y=85+(d.mesh.position.z-game.player.position.z)*sc;if(x>0&&x<170&&y>0&&y<170){ctx.fillStyle='#0f0';ctx.fillRect(x-2,y-2,4,4)}}ctx.fillStyle='#0ff';ctx.beginPath();ctx.arc(85,85,4,0,Math.PI*2);ctx.fill()}
let last=performance.now();function loop(){requestAnimationFrame(loop);const now=performance.now(),dt=Math.min((now-last)/16.67,3);last=now;if(!game.started){game.renderer.render(game.scene,game.camera);return}updatePlayer(dt);game.weapons.update(dt);game.grenades.update(dt);game.loot.update(dt);game.heatSystem.update(dt);game.missions.update(dt);updateAI(dt);for(let i=game.tracers.length-1;i>=0;i--){const t=game.tracers[i];t.life-=dt;t.line.material.opacity=t.life/8;if(t.life<=0){game.scene.remove(t.line);game.tracers.splice(i,1)}}for(let i=game.fx.length-1;i>=0;i--){const f=game.fx[i];f.life-=dt;f.mesh.material.opacity=f.life/45;if(f.life<=0){game.scene.remove(f.mesh);game.fx.splice(i,1)}}updateUI();drawMini();game.renderer.render(game.scene,game.camera)}loop();
window.__NEON_CITY_LOADED__=true;
addEventListener('resize',()=>{game.camera.aspect=innerWidth/innerHeight;game.camera.updateProjectionMatrix();game.renderer.setSize(innerWidth,innerHeight)});
